# Generated by Django 5.0.3 on 2024-04-19 16:51

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='age',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='duration',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='fitness',
            field=models.CharField(default='Full Body', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='other',
            field=models.TextField(default=builtins.input),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='typeofworkout',
            field=models.CharField(default='Full Body', max_length=50),
            preserve_default=False,
        ),
    ]
