# Generated by Django 5.0.3 on 2024-04-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_passwd_member_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
