# Generated by Django 5.0.3 on 2024-04-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_member_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='username',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='member',
            name='lname',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
