# Generated by Django 5.0.3 on 2024-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_prompt_typeofworkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='fitness',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
