# Generated by Django 5.0.3 on 2024-04-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_prompt_age_alter_prompt_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
