# Generated by Django 5.0.3 on 2024-04-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_prompt_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='typeofextra',
            field=models.CharField(default=12312, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prompt',
            name='age',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prompt',
            name='duration',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prompt',
            name='fitness',
            field=models.CharField(default=4234, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prompt',
            name='gender',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prompt',
            name='typeofworkout',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
