# Generated by Django 5.0.3 on 2024-04-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_signupmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpMember',
        ),
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
