# Generated by Django 5.0.3 on 2024-04-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_signupmember_remove_member_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
