# Generated by Django 5.0.3 on 2024-04-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_prompt_typeofextra_alter_prompt_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
