# Generated by Django 5.0.3 on 2024-04-19 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_prompt_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('different_sentence', models.TextField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('weightgoal', models.IntegerField()),
                ('weightcontrol', models.CharField(max_length=50)),
                ('foodAllergies', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
