# Generated by Django 5.0.3 on 2024-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_dietprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietprompt',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietprompt',
            name='weightcontrol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dietprompt',
            name='weightgoal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
