# Generated by Django 5.0.3 on 2024-04-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_dietprompt_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietprompt',
            name='different_sentence',
        ),
    ]
