# Generated by Django 5.0.3 on 2024-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_workoutprompt_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='different_sentence',
            field=models.TextField(default=1234),
            preserve_default=False,
        ),
    ]
