# Generated by Django 5.0.3 on 2024-04-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_dietprompt_different_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietprompt',
            name='typeofdiet',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
