# Generated by Django 5.0.3 on 2024-04-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_dietprompt_typeofdiet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietprompt',
            name='foodAllergies',
            field=models.CharField(max_length=300),
        ),
    ]
