# Generated by Django 5.0.3 on 2024-04-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_dietprompt_foodallergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietprompt',
            name='foodAllergies',
            field=models.CharField(max_length=50),
        ),
    ]
