# Generated by Django 5.0.3 on 2024-04-21 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_dietoutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_output', models.TextField()),
                ('workout_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.prompt')),
            ],
        ),
    ]
